### ISSUE TITLE
Form eklenmesi

### ISSUE THREAD

**Issue by semihokanpehlivan** [semihokanpehlivan/malima#1]
- yeni_iş.html sayfasında kullanıcının iletişim bilgileri olucak.

> Başlık, Müşteri ad soyad tc / şirket ise ünvan vergi no
> mail, adres, sabit ve gsm numaraları

- yeni_iş.html sayfasında kullanıcının istekleri olucak

> Başlangış,bitiş tarih ve saat
> Kişi sayısı ve kişi birim fiyatı
> Menüler combobox olucak
> Menülerde olmayan ekstralar için ekstalar ve toplam fiyatı olucak
> Ekstra hizmetler eklenebilicek artıya bastıkça gelicek ve comboboxtan seçilicek
> Açıklama kısmı olucak

**Comment by semihokanpehlivan** [comment]
Menüler combobox olur dedik ama birden fazla seçim yapabilicek şekilde olsa iyi olur bootstrap ın öyle componenti var. Yada daha farklı bir component düşündüysen onuda koyabilirsin yeterki birden fazla seçebileyim.

**Comment by ufukomer** [comment]
"Menülerde olmayan ekstralar için ekstalar ve toplam fiyatı olucak"

Bu neydi? Bugun bahsettigin pop-up olayi mi?

**Comment by ufukomer** [comment]
Bir kismi bitti, kontrol etsene --> 49e8d8ccc52af530c482fbc8650d2c9963599bb2

Not: Root directoy'de `bower install` yap. Bunun icinde pc'ne bower kurman lazim: 

```
npm install -g bower
```

👯    👯    👯

**Comment by ufukomer** [comment]
Goruntudeki kaymayi hallettim -> a31ac9e57e7e97aa16fe8b1375912b9a1d773d98

Zorunlu field'lari soyleyecektin?

**Comment by semihokanpehlivan** [comment]
onu soramadim yaa baska bi lafa tuttular beni :)

22 Ağustos 2016 Pazartesi tarihinde, Ömer Ufuk Efendioğlu <
notifications@github.com> yazdı:
