### ISSUE TITLE
Yeni_iş.html içine menu combobox eklenmesi

### ISSUE THREAD

**Issue by semihokanpehlivan** [semihokanpehlivan/malima#5]
Şimdilik basit bir combobox eklemesi yap, içine dummy-menu1 menu2 yaz. Multichoose yapma o bilgiyi tam doğrulayim ondan sonra multi yaparsin ;)

**Comment by ufukomer** [comment]
Bu alanin adi menu mu?

Asagidaki gibi bir sey mi ekleyeyim simdilik?


<img width="301" alt="screen shot 2016-08-25 at 2 03 02 pm" src="https://cloud.githubusercontent.com/assets/7649229/17966871/a8b645aa-6acc-11e6-975e-056238d2915f.png">

**Comment by semihokanpehlivan** [comment]
durumu kısmı olucak bunların altına aynı comboboxtan menü eklemek için olucak. Ama birden fazla seçebiliriz ileride o durum var.

**Comment by semihokanpehlivan** [comment]
68a0b8a5234f2bba28685d973e71bcfbe9075553
